refactor(#31): remove token from codebuild env
Signed-off-by: Mykyta Mozghovoi <n.mozgowoi2017@gmail.com>

diff --git a/aws/buildspecs/ci-cd-infrastructure/plan.yml b/aws/buildspecs/ci-cd-infrastructure/plan.yml
--- a/aws/buildspecs/ci-cd-infrastructure/plan.yml
+++ b/aws/buildspecs/ci-cd-infrastructure/plan.yml
@@ -16,8 +16,19 @@ phases:
       - "cd ${CODEBUILD_SRC_DIR}"
       - "echo ## TERRASPACE Init : Initialize all providers and modules"
       - "make terraspace-all-init"
-      - export GITHUB_TOKEN=$(echo "$GITHUB_TOKEN" | jq -r '.token')
-      - echo $GITHUB_TOKEN
+      - |
+        echo "Retrieving and using GitHub token for authentication..."
+        SECRET_ID=$(aws secretsmanager list-secrets --query "SecretList[?starts_with(Name, 'github-token-') && DeletedDate==null].Name" --output text)
+        if [ -z "$SECRET_ID" ]; then
+          echo "Error: No active GitHub token secret found."
+          exit 1
+        fi
+        GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id "$SECRET_ID" --query 'SecretString' --output text | jq -r '.token')
+        if [ -z "$GITHUB_TOKEN" ]; then
+          echo "Error: Failed to retrieve GitHub token."
+          exit 1
+        fi
+        echo "GitHub token retrieved successfully."
       - "echo ## TERRASPACE PLAN : Generate the Terraform Plan"
       - 'make terraspace-plan-file stack="ci-cd-infrastructure" out="ci-cd-infrastructure.plan"'
       - 'make terraspace-plan-file stack="ci-cd-iam" out="ci-cd-iam.plan"'
