fix(#42): update cloudfront function upload

diff --git a/aws/buildspecs/website/up.yml b/aws/buildspecs/website/up.yml
--- a/aws/buildspecs/website/up.yml
+++ b/aws/buildspecs/website/up.yml
@@ -22,13 +22,28 @@ phases:
       - "git clone $WEBSITE_GIT_REPOSITORY_LINK"
       - "echo Copying CloudFront routing script from cloned repo..."
       - "cp website/scripts/cloudfront_routing.js ./output/cloudfront_routing.js"
-      - echo "Updating CloudFront function..."
-      - aws cloudfront update-function --name routing-function \
-        --function-config "Comment=Routing logic for CloudFront,Runtime=cloudfront-js-1.0" \
-        --if-match $(aws cloudfront describe-function --name routing-function --query 'ETag' --output text) \
-        --function-code fileb://cloudfront_routing.js
-      - echo "Cleaning up..."
-      - rm -rf website
+      - "echo Updating CloudFront function..."
+      - |
+        aws cloudfront update-function --name routing-function \
+          --function-config 'Comment=Routing logic for CloudFront,Runtime=cloudfront-js-1.0' \
+          --if-match $(aws cloudfront describe-function --name routing-function --query 'ETag' --output text) \
+          --function-code fileb://./output/cloudfront_routing.js
+        if [ $? -ne 0 ]; then
+          echo "Error updating CloudFront function"
+          exit 1
+        fi
+      - "echo Cleaning up..."
+      - "rm -rf website"
+      - "echo Publishing the updated function..."
+      - |
+        aws cloudfront publish-function --name routing-function
+        if [ $? -ne 0 ]; then
+          echo "Error publishing CloudFront function"
+          exit 1
+        fi
+      - "echo Function published successfully"
+      - "echo Cleaning up..."
+      - "rm -rf website"
       - "aws codepipeline start-pipeline-execution --name $CI_CD_WEBSITE_PIPELINE_NAME"
 
 artifacts:
