refactor(#118): edit python diagrams and change comment place

diff --git a/aws/buildspecs/sandbox/deploy.yml b/aws/buildspecs/sandbox/deploy.yml
--- a/aws/buildspecs/sandbox/deploy.yml
+++ b/aws/buildspecs/sandbox/deploy.yml
@@ -17,14 +17,15 @@ phases:
 
   build:
     commands:
-      - "echo #### Build Project"
-      - 'make build || { echo "Build failed"; exit 1; }'
       - |
-        COMMENT_BODY="Deployment has started for version: http://$PROJECT_NAME-$BRANCH_NAME.s3-website.$AWS_DEFAULT_REGION.amazonaws.com"
+        COMMENT_BODY="Deployment has started for version: http://$PROJECT_NAME-$BRANCH_NAME.s3-website.$AWS_DEFAULT_REGION.amazonaws.com 
+        Please wait until the latest version is ready"
         if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"; then
           echo "Failed to add comment to PR"
           exit 1
         fi
+      - "echo #### Build Project"
+      - 'make build || { echo "Build failed"; exit 1; }'
       - 'aws s3 sync ./out s3://$PROJECT_NAME-$BRANCH_NAME || { echo "S3 sync failed"; exit 1; }'
       - "echo #### Check for bucket creation and decide on PR comment"
       - "bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh"
