refactor(#148): remove validation and add variables checks

diff --git a/aws/buildspecs/sandbox/deploy.yml b/aws/buildspecs/sandbox/deploy.yml
--- a/aws/buildspecs/sandbox/deploy.yml
+++ b/aws/buildspecs/sandbox/deploy.yml
@@ -5,6 +5,16 @@ phases:
     runtime-versions:
       nodejs: $NODEJS_VERSION
     commands:
+      - |
+        if [ -z "${BRANCH_NAME}" ]; then
+          echo "Error: Required environment variable BRANCH_NAME is not set or empty."
+          exit 1
+        fi
+
+        if [ -z "${PR_NUMBER}" ]; then
+          echo "Error: Required environment variable PR_NUMBER is not set or empty."
+          exit 1
+        fi
       - "bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/sandbox_installation.sh"
       - "cd ${WEBSITE_DIR:-/codebuild-user/website}"
       - "sudo apt update"
diff --git a/aws/buildspecs/sandbox/healthcheck.yml b/aws/buildspecs/sandbox/healthcheck.yml
--- a/aws/buildspecs/sandbox/healthcheck.yml
+++ b/aws/buildspecs/sandbox/healthcheck.yml
@@ -24,6 +24,16 @@ phases:
   build:
     commands:
       - |
+        if [ -z "${BRANCH_NAME}" ]; then
+          echo "Error: Required environment variable BRANCH_NAME is not set or empty."
+          exit 1
+        fi
+
+        if [ -z "${IS_PULL_REQUEST}" ]; then
+          echo "Error: Required environment variable IS_PULL_REQUEST is not set or empty."
+          exit 1
+        fi
+      - |
         echo "## Preparing Health Check for S3 Bucket..."
         BUCKET_URL="https://${PROJECT_NAME}-${BRANCH_NAME}.s3.${AWS_DEFAULT_REGION}.amazonaws.com"
 
diff --git a/aws/buildspecs/sandbox/up.yml b/aws/buildspecs/sandbox/up.yml
--- a/aws/buildspecs/sandbox/up.yml
+++ b/aws/buildspecs/sandbox/up.yml
@@ -5,6 +5,16 @@ phases:
     runtime-versions:
       python: $PYTHON_VERSION
     commands:
+      - |
+        if [ -z "${BRANCH_NAME}" ]; then
+          echo "Error: Required environment variable BRANCH_NAME is not set or empty."
+          exit 1
+        fi
+
+        if [ -z "${IS_PULL_REQUEST}" ]; then
+          echo "Error: Required environment variable IS_PULL_REQUEST is not set or empty."
+          exit 1
+        fi
       - ". ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/credentials.sh"
   build:
     commands:
