refactor(#142): add timestamp for token and edit token retrive

diff --git a/aws/buildspecs/sandbox/deploy.yml b/aws/buildspecs/sandbox/deploy.yml
--- a/aws/buildspecs/sandbox/deploy.yml
+++ b/aws/buildspecs/sandbox/deploy.yml
@@ -10,7 +10,8 @@ phases:
       - "sudo apt update"
       - 'sudo apt install gh -y || { echo "Failed to install GitHub CLI"; exit 1; }'
       - |
-        aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | gh auth login --with-token || {
+        echo "Retrieving and using GitHub token for authentication..."
+        aws secretsmanager get-secret-value --secret-id github-token --query 'SecretString' --output text | jq -r '.token' | gh auth login --with-token || {
           echo "GitHub authentication failed"
           exit 1
         }
@@ -20,6 +21,10 @@ phases:
       - |
         COMMENT_BODY="The deployment process for the sandbox has started.
         Please wait until the latest version is ready"
+        aws secretsmanager get-secret-value --secret-id github-token --query 'SecretString' --output text | jq -r '.token' | gh auth login --with-token || {
+          echo "GitHub authentication failed"
+          exit 1
+        }
         if ! gh pr comment "$PR_NUMBER" -R "$GITHUB_REPOSITORY" --body "$COMMENT_BODY"; then
           echo "Failed to add comment to PR"
           exit 1
