refactor(#110): add marker file

diff --git a/aws/buildspecs/sandbox/deploy.yml b/aws/buildspecs/sandbox/deploy.yml
--- a/aws/buildspecs/sandbox/deploy.yml
+++ b/aws/buildspecs/sandbox/deploy.yml
@@ -16,5 +16,14 @@ phases:
       - 'make build || { echo "Build failed"; exit 1; }'
       - "echo #### Deploy Project"
       - 'aws s3 sync ./out s3://$PROJECT_NAME-$BRANCH_NAME || { echo "S3 sync failed"; exit 1; }'
-      - "echo #### Create pull request comment"
-      - "bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh"
+      - "echo #### Check for bucket creation and decide on PR comment"
+      - |
+        MARKER_PATH=".markers/bucket_created.txt"
+        if aws s3api head-object --bucket $PROJECT_NAME-$BRANCH_NAME --key $MARKER_PATH > /dev/null 2>&1; then
+          echo "Bucket was created in this run. Proceeding to create PR comment."
+          bash ${CODEBUILD_SRC_DIR}/${SCRIPT_DIR}/sh/create_pr_comment.sh
+          # Удаляем маркерный файл после создания комментария
+          aws s3 rm s3://$PROJECT_NAME-$BRANCH_NAME/$MARKER_PATH || { echo "Failed to delete marker file"; exit 1; }
+        else
+          echo "Bucket already existed. Skipping PR comment creation."
+        fi
